%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2019 by California Institute of Technology.  ALL RIGHTS RESERVED. %
% United  States  Government  sponsorship  acknowledged.   Any commercial use %
% must   be  negotiated  with  the  Office  of  Technology  Transfer  at  the %
% California Institute of Technology.                                         %
%                                                                             %
% This software may be subject to  U.S. export control laws  and regulations. %
% By accepting this document,  the user agrees to comply  with all applicable %
% U.S. export laws and regulations.  User  has the responsibility  to  obtain %
% export  licenses,  or  other  export  authority  as may be required  before %
% exporting  such  information  to  foreign  countries or providing access to %
% foreign persons.                                                            %
%                                                                             %
% This  software  is a copy  and  may not be current.  The latest  version is %
% maintained by and may be obtained from the Mobility  and  Robotics  Sytstem %
% Section (347) at the Jet  Propulsion  Laboratory.   Suggestions and patches %
% are welcome and should be sent to the software's maintainer.                %
%                                                                             %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [] = create_spacecraft(Swarm, Small_body_model, output_folder)
%CREATE_SPACECRAFT Creates files Orb_SC_X.txt and SC_X for 42 simulation
% from a Swarm object
% Syntax: [] = create_spacecraft(Swarm, Small_body_model, output_folder)
% The function creates files Orb_SC_X.txt and SC_X describing the orbits of
% each spacecraft in the Swarm. The files are placed in output_folder.

if nargin<3
    output_folder='Eros';
end

[mkdir_success, mkdir_warn] = mkdir(output_folder);
for orbit_ix = 0:Swarm.get_num_spacecraft()-1

    radius_and_velocity = Swarm.abs_trajectory_array(1,:,orbit_ix+1);
    radius_m = radius_and_velocity(1:3);
    velocity_ms = radius_and_velocity(4:6);
    
    gm_m3sm2 = Small_body_model.BodyModel.gravity.gm*1e9;
    
    [a,e,i_anomaly,Omega,omega,theta]=rv2op(radius_m,velocity_ms,gm_m3sm2);
    
    
    periapsis_altitude_km = a*(1-e)*1e-3;
    apoapsis_altitude_km = a*(1+e)*1e-3;
    inclination_deg = i_anomaly*180/pi;
    raan_deg = Omega*180/pi;
    argument_periapsis_deg = omega*180/pi;
    true_anomaly_deg = theta*180/pi;
    
    orbit_header_str = [ ...
    "<<<<<<<<<<<<<<<<<  42: Orbit Description File   >>>>>>>>>>>>>>>>>", ...
    "Orbit around Eros             !  Description", ...
    "CENTRAL                       !  Orbit Type (ZERO, FLIGHT, CENTRAL, THREE_BODY)", ...
    "::::::::::::::  Use these lines if ZERO           :::::::::::::::::", ...
    "MINORBODY_2                   !  World", ...
    "FALSE                         ! Use Polyhedron Gravity", ...
    "::::::::::::::  Use these lines if FLIGHT   :::::::::::::::::", ...
    "0                             !  Region Number", ...
    "FALSE                         ! Use Polyhedron Gravity", ...
    ];

    orbit_str = [ ...
      "::::::::::::::  Use these lines if Body-Centered Orbit  :::::::::::::::::", ...
    "MINORBODY_1                   !  Orbit Center", ...
    "FALSE                         !  Secular Orbit Drift Due to J2", ...
    "KEP                           !  Use Keplerian elements (KEP) or (RV) or FILE", ...
    "PA                            !  Use Peri/Apoapsis (PA) or min alt/ecc (AE)", ...
    sprintf("%.1f  %.1f                    !  Periapsis & Apoapsis Altitude, km", periapsis_altitude_km, apoapsis_altitude_km), ...
    "0.0  0.0                    !  Min Altitude (km), Eccentricity", ...
    sprintf("%.1f                          !  Inclination (deg)", inclination_deg), ...
    sprintf("%.1f                         !  Right Ascension of Ascending Node (deg)",raan_deg), ...
    sprintf("%.1f                          !  Argument of Periapsis (deg)",argument_periapsis_deg), ...
    sprintf("%.1f                         !  True Anomaly (deg)",true_anomaly_deg), ...
    "0.0  0.0  0.0                 !  RV Initial Position (km)", ...
    "0.0  0.0  0.0                 !  RV Initial Velocity (km/sec)", ...
    "TRV  ""ORB_ID""                 !  TLE or TRV format, Label to find in file", ... % Note that this is not actually read and does not matter.
    """TRV.txt""                     !  File name", ...  
    ];

    % None of the footer is used, since we specify a CENTER orbit.
    orbit_footer_str = [... 
    ":::::::::::::  Use these lines if Three-Body Orbit  ::::::::::::::::", ...
    "SUNEARTH                      !  Lagrange system", ...
    "LAGDOF_MODES                  !  Propagate using LAGDOF_MODES or LAGDOF_COWELL or LAGDOF_SPLINE", ...
    "MODES                         !  Initialize with MODES or XYZ or FILE", ...
    "L2                            !  Libration point (L1, L2, L3, L4, L5)", ...
    "800000.0                      !  XY Semi-major axis, km", ...
    "45.0                          !  Initial XY Phase, deg", ...
    "CW                            !  Sense (CW, CCW), viewed from +Z", ...
    "0.0                           !  Second XY Mode Semi-major Axis, km (L4, L5 only)", ...
    "0.0                           !  Second XY Mode Initial Phase, deg (L4, L5 only)", ...
    "CW                            !  Sense (CW, CCW), viewed from +Z (L4, L5 only)", ...
    "400000.0                      !  Z Semi-axis, km", ...
    "60.0                          !  Initial Z Phase, deg", ...
    "1.05  0.5  0.0                !  Initial X, Y, Z (Non-dimensional)", ...
    "0.0   0.0  0.0                !  Initial Xdot, Ydot, Zdot (Non-dimensional)", ...
    "TRV  ""ORB_ID""                 !  TLE, TRV or SPLINE format, Label to find in file", ...
    """TRV.txt""                     !  File name", ...
    "******************* Formation Frame Parameters ************************", ...
    "N                             !  Formation Frame Fixed in [NL]", ...
    "0.0  0.0  0.0  123            !  Euler Angles (deg) and Sequence", ...
    "N                             !  Formation Origin expressed in [NL]", ...
    "0.0  0.0  0.0                 !  Formation Origin wrt Ref Orbit (m)", ...
    ];

    inp_sim_file = fopen(fullfile(output_folder,sprintf("Orb_SC_%d.txt",orbit_ix)),'w');
    for line = orbit_header_str
        fprintf(inp_sim_file, "%s\n", line );
    end
    for line = orbit_str
        fprintf(inp_sim_file, "%s\n", line );
    end
    for line = orbit_footer_str
        fprintf(inp_sim_file, "%s\n", line );
    end
    fclose(inp_sim_file);
    
    spacecraft_string_header= [ ...
    "<<<<<<<<<<<<<<<<<  42: Spacecraft Description File   >>>>>>>>>>>>>>>>>", ...
    ];

    spacecraft_string_name = [ ...
        sprintf(" S/C %d of type %d      !  Description",orbit_ix,Swarm.Parameters.types{orbit_ix+1}), ...
        sprintf("""ION_%d_T%d""                         !  Label",orbit_ix,Swarm.Parameters.types{orbit_ix+1}), ...
        "GenScSpriteAlpha.ppm          !  Sprite File Name", ...
        "PROTOTYPE_FSW                 !  Flight Software Identifier", ...
        "0.2                           !  FSW Sample Time, sec", ...
        ];
    
    spacecraft_string_footer = [ ...
    "************************* Orbit Parameters ****************************", ...
    "ENCKE                         !  Orbit Prop FIXED, EULER_HILL, or ENCKE", ...
    "CM                            !  Pos of CM or ORIGIN, wrt F", ...
    "0.0  0.0  0.0                 !  Pos wrt Formation (m), expressed in F", ...
    "0.0  0.0  0.0                 !  Vel wrt Formation (m/s), expressed in F", ...
    "*************************** Initial Attitude ***************************", ...
    "LAL                           ! Ang Vel wrt [NL], Att [QA] wrt [NLF]", ...
    "0.0    0.0    0.0             ! Ang Vel (deg/sec)", ...
    "0.0    0.0    0.0    1.0      ! Quaternion", ...
    "0.0    0.0    0.0    213      ! Angles (deg) & Euler Sequence", ...
    "***************************  Dynamics Flags  ***************************", ...
    "DYN_JOINT                     ! Rotation STEADY, KIN_JOINT, or DYN_JOINT", ...
    "FALSE                         ! Passive Joint Forces and Torques Enabled", ...
    "FALSE                         ! Compute Constraint Forces and Torques", ...
    "REFPT_CM                      ! Mass Props referenced to REFPT_CM or REFPT_JOINT", ...
    "FALSE                         ! Flex Active", ...
    "FALSE                         ! Include 2nd Order Flex Terms", ...
    "2.0                           ! Drag Coefficient", ...
    "************************************************************************", ...
    "************************* Body Parameters ******************************", ...
    "************************************************************************", ...
    "1                             ! Number of Bodies", ...
    "================================ Body 0 ================================", ...
    "200.0                         ! Mass", ...
    "100.0  200.0  300.0           ! Moments of Inertia (kg-m^2)", ...
    "0.0  0.0  0.0                 ! Products of Inertia (xy,xz,yz)", ...
    "0.0  0.0  0.0                 ! Location of mass center, m", ...
    "0.0  0.0  0.0                 ! Constant Embedded Momentum (Nms)", ...
    "IonCruiser.obj                ! Geometry Input File Name", ...
    "NONE                          ! Flex File Name", ...
    "************************************************************************", ...
    "*************************** Joint Parameters ***************************", ...
    "************************************************************************", ...
    "         (Number of Joints is Number of Bodies minus one)", ...
    "============================== Joint 0 ================================", ...
    "0 1                           ! Inner, outer body indices", ...
    "1   213   GIMBAL              ! RotDOF, Seq, GIMBAL or SPHERICAL", ...
    "0   123                       ! TrnDOF, Seq", ...
    "FALSE  FALSE  FALSE           ! RotDOF Locked", ...
    "FALSE  FALSE  FALSE           ! TrnDOF Locked", ...
    "0.0    0.0    0.0             ! Initial Angles [deg]", ...
    "0.0    0.0    0.0             ! Initial Rates, deg/sec", ...
    "0.0    0.0    0.0             ! Initial Displacements [m]", ...
    "0.0    0.0    0.0             ! Initial Displacement Rates, m/sec", ...
    "0.0   0.0  0.0  312           ! Bi to Gi Static Angles [deg] & Seq", ...
    "0.0   0.0  0.0  312           ! Go to Bo Static Angles [deg] & Seq", ...
    "0.0   0.0  0.0                ! Position wrt inner body origin, m", ...
    "0.0   0.0  0.0                ! Position wrt outer body origin, m", ...
    "0.0   0.0  0.0                ! Rot Passive Spring Coefficients (Nm/rad)", ...
    "0.0   0.0  0.0                ! Rot Passive Damping Coefficients (Nms/rad)", ...
    "0.0   0.0  0.0                ! Trn Passive Spring Coefficients (N/m)", ...
    "0.0   0.0  0.0                ! Trn Passive Damping Coefficients (Ns/m)", ...
    "*************************** Wheel Parameters ***************************", ...
    "0                             ! Number of wheels", ...
    "=============================  Wheel 0  ================================", ...
    "0.0                           ! Initial Momentum, N-m-sec", ...
    "1.0   0.0   0.0               ! Wheel Axis Components, [X, Y, Z]", ...
    "0.14   50.0                   ! Max Torque (N-m), Momentum (N-m-sec)", ...
    "0.012                         ! Wheel Rotor Inertia, kg-m^2", ...
    "0.48                          ! Static Imbalance, g-cm", ...
    "13.7                          ! Dynamic Imbalance, g-cm^2", ...
    "0                             ! Flex Node Index", ...
    "**************************** MTB Parameters ****************************", ...
    "0                                   ! Number of MTBs", ...
    "==============================  MTB 0  =================================", ...
    "180.0                         ! Saturation (A-m^2)", ...
    "1.0   0.0   0.0               ! MTB Axis Components, [X, Y, Z]", ...
    "************************* Thruster Parameters **************************", ...
    "0                             ! Number of Thrusters", ...
    "==============================  Thr 0  =================================", ...
    "1.0                          ! Thrust Force (N)", ...
    "0  -1.0  0.0  0.0             ! Body, Thrust Axis ", ...
    " 1.0  1.0  1.0                ! Location in B0, m", ...
    "0                             ! Flex Node Index", ...
    "******************************* Gyro ************************************", ...
    "0                                ! Number of Gyro Axes", ...
    "============================== Axis 0 ===================================", ...
    "0.1                           ! Sample Time,sec", ...
    "1.0  0.0  0.0                 ! Axis expressed in Body Frame", ...
    "1000.0                        ! Max Rate, deg/sec", ...
    "100.0                         ! Scale Factor Error, ppm", ...
    "1.0                           ! Quantization, arcsec ", ...
    "0.07                          ! Angle Random Walk (deg/rt-hr)", ...
    "0.1  1.0                      ! Bias Stability (deg/hr) over timespan (hr)", ...
    "0.1                           ! Angle Noise, arcsec RMS", ...
    "0.1                           ! Initial Bias (deg/hr)", ...
    "0                             ! Flex Node Index", ...
    "*************************** Magnetometer ********************************", ...
    "0                             ! Number of Magnetometer Axes", ...
    "============================== Axis 0 ===================================", ...
    "0.1                           ! Sample Time,sec", ...
    "1.0  0.0  0.0                 ! Axis expressed in Body Frame", ...
    "60.0E-6                       ! Saturation, Tesla", ...
    "0.0                           ! Scale Factor Error, ppm", ...
    "1.0E-6                        ! Quantization, Tesla ", ...
    "1.0E-6                        ! Noise, Tesla RMS", ...
    "0                             ! Flex Node Index", ...
    "*********************** Coarse Sun Sensor *******************************", ...
    "0                             ! Number of Coarse Sun Sensors", ...
    "============================== CSS 0 ====================================", ...
    "0.1                           ! Sample Time,sec", ...
    "1.0  1.0  1.0                 ! Axis expressed in Body Frame", ...
    "90.0                          ! Half-cone Angle, deg", ...
    "1.0                           ! Scale Factor", ...
    "0.001                         ! Quantization", ...
    "************************* Fine Sun Sensor *******************************", ...
    "0                             ! Number of Fine Sun Sensors", ...
    "=============================== FSS 0 ===================================", ...
    "0.2                           ! Sample Time,sec", ...
    "30.0  20.0  10.0  213         ! Mounting Angles (deg), Seq in Body", ...
    "32.0   32.0                   ! X, Y FOV Size, deg", ...
    "0.1                           ! Noise Equivalent Angle, deg RMS", ...
    "0.5                           ! Quantization, deg", ...
    "************************** Star Tracker *********************************", ...
    "0                             ! Number of Star Trackers", ...
    "=============================== ST 0 ====================================", ...
    "0.25                          ! Sample Time,sec", ...
    "30.0  20.0  10.0  213         ! Mounting Angles (deg), Seq in Body", ...
    "8.0   8.0                     ! X, Y FOV Size, deg", ...
    "30.0  10.0  10.0              ! Sun, Earth, Moon Exclusion Angles, deg", ...
    "2.0  2.0  20.0                ! Noise Equivalent Angle, arcsec RMS", ...
    "0                             ! Flex Node Index", ...
    "****************************** GPS **************************************", ...
    "0                             ! Number of GPS Receivers", ...
    "============================= GPSR 0 ====================================", ...
    "0.25                          ! Sample Time,sec", ...
    "4.0                           ! Position Noise, m RMS", ...
    "0.02                          ! Velocity Noise, m/sec RMS", ...
    "20.0E-9                       ! Time Noise, sec RMS", ...
    "*************************** Accelerometer *******************************", ...
    "0                             ! Number of Accel Axes", ...
    "============================== Axis 0 ===================================", ...
    "0.1                           ! Sample Time,sec", ...
    "0.5  1.0  1.5                 ! Position in B[0] (m)", ...
    "1.0  0.0  0.0                 ! Axis expressed in Body Frame", ...
    "0.0                           ! Scale Factor Error", ...
    "0.05                          ! Quantization, m/s^2", ...
    "0.0                           ! Random Walk (units?)", ...
    "0.0                           ! Bias Stability (m/s^2/hr?)", ...
    "0.0                           ! DV Noise, m/s", ...
    "0.5                           ! Initial Bias (m/s^2)", ...
    "0                             ! Flex Node Index", ...
    ];

    inp_sc_file = fopen(fullfile(output_folder,sprintf("SC_%d.txt",orbit_ix)),'w');
    for line = spacecraft_string_header
        fprintf(inp_sc_file, "%s\n", line );
    end
    for line = spacecraft_string_name
        fprintf(inp_sc_file, "%s\n", line );
    end
    for line = spacecraft_string_footer
        fprintf(inp_sc_file, "%s\n", line );
    end
    fclose(inp_sc_file);
    
end